### ISSUE TITLE
An error about model version when using python client

### ISSUE THREAD

**Issue by lazykyama** [NVIDIA/dl-inference-server#17]
This is a trivial issue. When sending a request via a python client, a following error occurred.

```
Traceback (most recent call last):
  File "src/clients/python/image_client.py", line 263, in <module>
    FLAGS.model_name, FLAGS.model_version, FLAGS.verbose)
  File "/usr/local/lib/python2.7/dist-packages/tensorrtserver/api/__init__.py", line 453, in __init__
    model_name, imodel_version, verbose)))
ctypes.ArgumentError: argument 5: <type 'exceptions.TypeError'>: wrong type
```

This error seems to be caused by mismatching type of `FLAGS.model_version` parameter.
Python code takes this parameter as a `str` variable and gives this to `InferContext`. But a type of `model_version` in `InferContext` is an integer.

So, IMHO, we can fix this problem by changing type of the parameter in `ArgumentParser` as follows.

```
diff --git a/src/clients/python/image_client.py b/src/clients/python/image_client.py
index f04848c..309d7db 100755
--- a/src/clients/python/image_client.py
+++ b/src/clients/python/image_client.py
@@ -231,7 +231,7 @@ if __name__ == '__main__':
                         help='Enable verbose output')
     parser.add_argument('-m', '--model-name', type=str, required=True,
                         help='Name of model')
-    parser.add_argument('-x', '--model-version', type=str, required=False,
+    parser.add_argument('-x', '--model-version', type=int, required=False,
                         help='Version of model. Default is to use latest version.')
     parser.add_argument('-b', '--batch-size', type=int, required=False, default=1,
                         help='Batch size. Default is 1.')
```

**Comment by deadeyegoodwin** [comment]
Thanks for the bug report. Fixed in 18.09, 18.10 and master branches.

**Comment by giranntu** [comment]
Right now we are using int in this version, but when I tried the 

root@cd3db5703cd9:/workspace/src/clients/python# python grpc_image_client.py -u xx.xx.xx.xx(IP):8001 -m resnet50_netdef -x 5 -s INCEPTION Dog.jpg
Traceback (most recent call last):
  File "grpc_image_client.py", line 283, in <module>
    request.version = FLAGS.model_version
TypeError: 5 has type int, but expected one of: bytes, unicode

And when I try to modify to original **str**, which is int default in code.
It worked.

**Comment by giranntu** [comment]
But I still can not do the specify model version thru this argument....

Which we describe in document:

> All
>     All versions of the model that are specified in the model repository are available for inferencing. 
> Latest
>     Only the latest n versions of the model specified in the model repository are available for inferencing. The latest versions of the model are the numerically greatest version numbers. 
> Specific
>     The specifically listed versions of the model are available for inferencing. 


It would be nice if you guide that where could we get to specify the model version that we want to inference?

**Comment by deadeyegoodwin** [comment]
Thanks for pointing out the issue in grpc_image_client.py. The problem is that the GRPC protocol in grpc_service.proto is incorrect. The 'version' field should *not* be string, but should instead by *int*. We will fix this in the next release.
